image: ubuntu:latest

stages:
  - build
  - test
  - deploy staging
  - test staging
  - deploy production
  - test production

variables:
  APP_BASE_URL: http://(aws-s3-production-static-web-hosting-url)
  APP_BASE_URL_STAGING: http://(aws-s3-staging-static-web-hosting-url)

build job:
  image: node:16-alpine
  stage: build
  script:
    - yarn install 
    - yarn build
  artifacts:
    paths:
      - build

tests in production:
  image: curlimages/curl
  stage: test production
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - curl $APP_BASE_URL | grep "Flask App"

deploy to staging:
  stage: deploy staging
  image:
    name: amazon/aws-cli:2.4.11
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - echo "Hello S3" > test.txt
    - aws s3 sync build/ s3://$AWS_S3_BUCKET_STAGING --delete

deploy to production:
  stage: deploy production
  image:
    name: amazon/aws-cli:2.4.11
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - echo "Hello S3" > test.txt
    - aws s3 sync build/ s3://$AWS_S3_BUCKET --delete

tests in production:
  image: curlimages/curl
  stage: test production
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - curl $APP_BASE_URL | grep "Flask App"